In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
from scipy.spatial.distance import cdist
def eval_MAP_K(query_set, search_set, query_label, search_set_label, K):
    query_class_arr = query_set
    search_set_class_arr = search_set
    query_label_arr = query_label
    query_label_arr.astype(int)
    search_set_label_arr = search_set_label
    search_set_label_arr.astype(int)
    num_query_sample = query_label_arr.shape[0]
    dist_q_search_class = cdist(query_class_arr,search_set_class_arr,metric='euclidean')
    AP=0
    pre=0
    for query_count in range(0,num_query_sample):
      actual_label = query_label_arr[query_count]
      value=dist_q_search_class[query_count,:]
      sorted_value_idx=value.argsort()
      predicted_K_label = search_set_label_arr[sorted_value_idx[0:K]]
      L=np.sum((np.in1d(predicted_K_label,actual_label)).astype(int))
      P=0
      for r in range(0,K):
        rtr_label_r = predicted_K_label[:(r+1)]
        l=np.sum((np.in1d(rtr_label_r,actual_label)).astype(int))
        precision=l/(r+1)
        if actual_label==predicted_K_label[r]:
          delta=1
        else:
          delta=0
        P=P+(precision*delta)
      if L!=0:
        AP=AP+((1/L)*P)
    map_K=AP/num_query_sample
    return map_K

In [0]:
def get_skt_data():
  training_query_skt=[]
  training_query_label=[]
  z_s=[]
  q=0
  z=0
  for skt_fea in x_train_skt:
    z_s.append(skt_fea)
    training_query_skt.append(encoder_skt.predict(skt_fea.reshape(4096,1).transpose()))
    training_query_label.append(q)
    z=z+1
    if z%64 ==0:
      q=q+1
  return np.squeeze(np.asarray(training_query_skt)),np.asarray(training_query_label).reshape(5888,1),z_s

In [0]:
def get_img_data():
  training_search_img=[]
  training_search_img_label=[]
  z_i=[]
  p=0
  z=0
  for img_fea in x_train_img:
    z_i.append(img_fea)
    training_search_img.append(encoder_img.predict(img_fea.reshape(4096,1).transpose()))
    training_search_img_label.append(p)
    z=z+1
    if z%200 == 0:
      p=p+1
  return np.squeeze(np.asarray(training_search_img)),np.asarray(training_search_img_label).reshape(x_train_img.shape[0],1),z_i

In [0]:
#z=np.where(x_train_skt==x_train_skt[0])

In [0]:
def calc():
  training_query_skt,training_query_label,z_s=get_skt_data()
  training_search_img,training_search_img_label,z_i=get_img_data()
  return eval_MAP_K(training_query_skt,training_search_img,training_query_label,training_search_img_label,200)

In [0]:
import os
import numpy as np
dictionary={}
training_files='/content/gdrive/My Drive/Feature_Vectors/Sketchs/Training'
labels=os.listdir(training_files)
labels.sort()
x_train_skt=[]
y_train=[]
y_t=[]
a=0
for label in labels:
  skt_fea_names=os.listdir(os.path.join(training_files,label))
  for skt in skt_fea_names:
    skt_fea_path=os.path.join(training_files,label,skt)
    skt_fea=np.load(skt_fea_path)
    x_train_skt.append(skt_fea)
    y_t.append(a)
    y_train.append(label)
    a=a+1
x_train_skt=np.asarray(x_train_skt)

In [0]:
from sklearn.preprocessing import OneHotEncoder
ohe_skt=OneHotEncoder()
one_hot_skt=ohe_skt.fit_transform(np.asarray(y_train).reshape(92,64))
one_hot_skt=one_hot_skt.toarray()
one_hot_skt=one_hot_skt.transpose()

In [0]:
img_training_files='/content/gdrive/My Drive/TUB_200_Feat'
labels=os.listdir(img_training_files)
labels.sort()
x_train_img=[]
y_train_img=[]
y_t_i=[]
b=0
for label in labels:
  img_names=os.listdir(os.path.join(img_training_files,label))
  for img in img_names:
    img_fea_path=os.path.join(img_training_files,label,img)
    img_fea=np.load(img_fea_path)
    x_train_img.append(img_fea)
    y_t_i.append(b)
    y_train_img.append(label)
    b=b+1
x_train_img=np.asarray(x_train_img)

In [0]:
b

18410

In [0]:
import pandas as pd

In [0]:
temp=pd.DataFrame(y_train)

In [0]:
unique_labels=temp[0].unique()

In [0]:
unique_labels.sort()

In [0]:
a=unique_labels.reshape(92,1)

In [0]:
ohe_skt=OneHotEncoder()
one_hot_skt=ohe_skt.fit_transform(a)
one_hot_skt=one_hot_skt.toarray()
one_hot_skt=one_hot_skt.transpose()

In [0]:
one_hot_skt.shape

(92, 92)

In [0]:
f_one_hot_skt=[]
for row in one_hot_skt:
   for i in range(64):
    f_one_hot_skt.append(row)

In [0]:
f_one_hot_skt=np.asarray(f_one_hot_skt)

In [0]:
f_one_hot_skt[64]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [0]:
temp_img=pd.DataFrame(y_train_img)

In [0]:
temp_img[0].unique()

array(['alarm clock', 'arm', 'armchair', 'ashtray', 'axe', 'backpack',
       'banana', 'barn', 'baseball bat', 'basket', 'beer-mug',
       'binoculars', 'book', 'brain', 'bread', 'bridge', 'bulldozer',
       'bush', 'cake', 'camera', 'candle', 'cannon', 'castle',
       'chandelier', 'church', 'cloud', 'computer monitor',
       'computer-mouse', 'cow', 'crab', 'crocodile', 'dolphin', 'donut',
       'door', 'envelope', 'eyeglasses', 'fish', 'floor lamp', 'giraffe',
       'hedgehog', 'helicopter', 'hot air balloon', 'hot-dog',
       'hourglass', 'house', 'ice-cream-cone', 'ipod', 'kangaroo', 'key',
       'lighter', 'loudspeaker', 'mailbox', 'megaphone', 'microscope',
       'mosquito', 'motorbike', 'parking meter', 'parrot', 'pear', 'pen',
       'pigeon', 'pumpkin', 'race car', 'radio', 'revolver',
       'rollerblades', 'scissors', 'sea turtle', 'seagull', 'shark',
       'shoe', 'shovel', 'skateboard', 'skyscraper', 'snowboard', 'socks',
       'spider', 'spoon', 'streetlight'

In [0]:
unique_labels_img=temp_img[0].unique()

In [0]:
unique_labels_img.sort()

In [0]:
b=unique_labels_img.reshape(92,1)

In [0]:
b

array([['alarm clock'],
       ['arm'],
       ['armchair'],
       ['ashtray'],
       ['axe'],
       ['backpack'],
       ['banana'],
       ['barn'],
       ['baseball bat'],
       ['basket'],
       ['beer-mug'],
       ['binoculars'],
       ['book'],
       ['brain'],
       ['bread'],
       ['bridge'],
       ['bulldozer'],
       ['bush'],
       ['cake'],
       ['camera'],
       ['candle'],
       ['cannon'],
       ['castle'],
       ['chandelier'],
       ['church'],
       ['cloud'],
       ['computer monitor'],
       ['computer-mouse'],
       ['cow'],
       ['crab'],
       ['crocodile'],
       ['dolphin'],
       ['donut'],
       ['door'],
       ['envelope'],
       ['eyeglasses'],
       ['fish'],
       ['floor lamp'],
       ['giraffe'],
       ['hedgehog'],
       ['helicopter'],
       ['hot air balloon'],
       ['hot-dog'],
       ['hourglass'],
       ['house'],
       ['ice-cream-cone'],
       ['ipod'],
       ['kangaroo'],
       ['key'],
       ['li

In [0]:
ohe_img=OneHotEncoder()
one_hot_img=ohe_img.fit_transform(b)
one_hot_img=one_hot_img.toarray()
one_hot_img=one_hot_img.transpose()

In [0]:
one_hot_img.shape

(92, 92)

In [0]:
f_one_hot_img=[]
for col in one_hot_img:
  for j in range(0,200):
    f_one_hot_img.append(col)

In [0]:
f_one_hot_img=np.asarray(f_one_hot_img)

In [0]:
f_one_hot_img.shape

(18400, 92)

In [0]:
p=[]
for col in one_hot_img:
  for j in range(0,200):
    p.append(col)

In [0]:
p[199]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [0]:
row_=p[18399]
for i in range(10):
  p.append(row_)

In [0]:
p=np.asarray(p)

In [0]:
p.shape

(18410, 92)

In [0]:
one_hot_skt.shape

(92, 92)

In [0]:
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Model
from tensorflow.python.keras import regularizers

In [0]:
input_img = Input(shape=(4096,))
# "encoded" is the encoded representation of the input
encoded_img = Dense(92, activation='relu', kernel_regularizer=regularizers.l2(0.1))(input_img)
# "decoded" is the lossy reconstruction of the input
decoded_img = Dense(4096,activation='relu', kernel_regularizer=regularizers.l2(0.1))(encoded_img)

# this model maps an input to its reconstruction
autoencoder_img = Model(input_img, [decoded_img,encoded_img])

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
encoder_img = Model(input_img, encoded_img)

In [0]:
autoencoder_img.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4096)              0         
_________________________________________________________________
dense (Dense)                (None, 92)                376924    
_________________________________________________________________
dense_1 (Dense)              (None, 4096)              380928    
Total params: 757,852
Trainable params: 757,852
Non-trainable params: 0
_________________________________________________________________


In [0]:
encoder_img.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4096)              0         
_________________________________________________________________
dense (Dense)                (None, 92)                376924    
Total params: 376,924
Trainable params: 376,924
Non-trainable params: 0
_________________________________________________________________


In [0]:
input_skt = Input(shape=(4096,))
# "encoded" is the encoded representation of the input
encoded_skt = Dense(92,activation='relu',kernel_regularizer=regularizers.l2(0.1))(input_skt)
# "decoded" is the lossy reconstruction of the input
decoded_skt = Dense(4096, activation='relu', kernel_regularizer=regularizers.l2(0.1))(encoded_skt)

# this model maps an input to its reconstruction
autoencoder_skt = Model(input_skt, [decoded_skt,encoded_skt])

In [0]:
encoder_skt = Model(input_skt, encoded_skt)

In [0]:
autoencoder_skt.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 4096)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 92)                376924    
_________________________________________________________________
dense_3 (Dense)              (None, 4096)              380928    
Total params: 757,852
Trainable params: 757,852
Non-trainable params: 0
_________________________________________________________________


In [0]:
parllel=Model([input_skt,input_img],[decoded_skt,encoded_skt,decoded_img,encoded_img])

In [0]:
parllel.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 4096)         0                                            
__________________________________________________________________________________________________
input_1 (InputLayer)            (None, 4096)         0                                            
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 92)           376924      input_2[0][0]                    
__________________________________________________________________________________________________
dense (Dense)                   (None, 92)           376924      input_1[0][0]                    
__________________________________________________________________________________________________
dense_3 (D

In [0]:
from tensorflow.python.keras.optimizers import Adam 
autoencoder_img.compile(optimizer=Adam(lr=1e-4),loss=['mean_squared_error','mean_squared_error'])#,loss_weights=[100,8,100,1])

Instructions for updating:
Use tf.cast instead.


In [0]:
from tensorflow.python import keras
class callbacker(keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
      print("  MAP = {} ".format(calc()))
      return calc()

In [0]:
callbacked=callbacker()
z=autoencoder_img.fit(x_train_img,[x_train_img,p],epochs=150,shuffle=True,batch_size=128,verbose=1)#,callbacks=[callbacked])

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
18410/18410 [==============================] - 1s 70us/sample - loss: 23.5855 - dense_1_loss: 1.4538 - dense_loss: 0.1322
Epoch 2/150
18410/18410 [==============================] - 1s 45us/sample - loss: 7.8220 - dense_1_loss: 1.4507 - dense_loss: 0.0255
Epoch 3/150
18410/18410 [==============================] - 1s 44us/sample - loss: 2.9733 - dense_1_loss: 1.4355 - dense_loss: 0.0135
Epoch 4/150
18410/18410 [==============================] - 1s 45us/sample - loss: 1.7329 - dense_1_loss: 1.4219 - dense_loss: 0.0095
Epoch 5/150
18410/18410 [==============================] - 1s 44us/sample - loss: 1.4667 - dense_1_loss: 1.4096 - dense_loss: 0.0075
Epoch 6/150
18410/18410 [==============================] - 1s 45us/sample - loss: 1.4125 - dense_1_loss: 1.3979 - dense_loss: 0.0066
Epoch 7/150
18410/18410 [==============================] - 1s 44us/sample - loss: 1.3956 - dense_1_loss: 1.3873 - dense_loss: 0.0063
Epoch 8/150
18410/18

In [0]:
autoencoder_skt.compile(optimizer=Adam(lr=1e-4),loss=['mean_squared_error','mean_squared_error'])#,loss_weights=[100,8,100,1])

In [0]:
z=autoencoder_skt.fit(x_train_skt,[x_train_skt,f_one_hot_skt],epochs=150,shuffle=True,batch_size=128,verbose=1)#,callbacks=[callbacked])

Epoch 1/150
5888/5888 [==============================] - 0s 76us/sample - loss: 32.9064 - dense_3_loss: 1.6610 - dense_2_loss: 0.2500
Epoch 2/150
5888/5888 [==============================] - 0s 45us/sample - loss: 23.4637 - dense_3_loss: 1.6749 - dense_2_loss: 0.0500
Epoch 3/150
5888/5888 [==============================] - 0s 44us/sample - loss: 16.6220 - dense_3_loss: 1.6746 - dense_2_loss: 0.0360
Epoch 4/150
5888/5888 [==============================] - 0s 44us/sample - loss: 11.7523 - dense_3_loss: 1.6713 - dense_2_loss: 0.0259
Epoch 5/150
5888/5888 [==============================] - 0s 48us/sample - loss: 8.3485 - dense_3_loss: 1.6659 - dense_2_loss: 0.0199
Epoch 6/150
5888/5888 [==============================] - 0s 44us/sample - loss: 6.0124 - dense_3_loss: 1.6600 - dense_2_loss: 0.0163
Epoch 7/150
5888/5888 [==============================] - 0s 44us/sample - loss: 4.4386 - dense_3_loss: 1.6545 - dense_2_loss: 0.0142
Epoch 8/150
5888/5888 [==============================] - 0s 43us/

In [0]:
training_query_skt,training_query_label,z_s=get_skt_data()

In [0]:
z_s[0]

array([3.903205 , 0.       , 0.       , ..., 0.       , 0.421281 ,
       3.5883198], dtype=float32)

In [0]:
training_query_skt[5]

array([0.555003  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04083944, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04312199, 0.0334179 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0391528 , 0.03251652, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08238696, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [0]:
training_search_img,training_search_img_label,z_i=get_img_data()

In [0]:
training_search_img.shape

(18410, 92)

In [0]:
training_search_img_label[200]

array([1])

In [0]:
eval_MAP_K(training_query_skt,training_search_img,training_query_label,training_search_img_label,100)

0.5091247276138376